apiVersion: apps/v1
kind: Deployment
metadata:
  name: helm-deploy
spec:
  replicas: {{ .Values.replicaCount }} #1
  selector:
    matchLabels:
      app: devops
  template:
    metadata:
      labels:
        app: devops
    spec:
      containers:
        - name: my-nodeapp
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }} #myjavapp:latest 
          ports:
            - containerPort: {{ .Values.containerPort }}
      imagePullSecrets:
      - name: helm
